CREATE TABLE persona (
	codigo BIGSERIAL PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	direccion VARCHAR(30),
	numero VARCHAR(30),
	complemento VARCHAR(30),
	barrio VARCHAR(30),
	cep VARCHAR(30),
	ciudad VARCHAR(30),
	estado VARCHAR(30),
	activo BOOLEAN NOT NULL
);


insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Ennis Threadgould', '5 5th Junction', '22-571-0245', 'Golf View', '4806 Clemons Way', '346-17-2039', 'Tulsa', 'Oklahoma', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Vanda Montez', '2689 Sycamore Court', '55-651-4873', 'Del Sol', '6224 Sunfield Circle', '627-60-6948', 'Albuquerque', 'New Mexico', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Virgie Maundrell', '388 Transport Alley', '83-739-3717', 'Burning Wood', '41 Larry Park', '416-84-0441', 'Norman', 'Oklahoma', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Carly Sheals', '633 Calypso Trail', '42-574-4590', 'Bartelt', '151 Lukken Trail', '186-06-4774', 'Lafayette', 'Louisiana', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Randie Mabey', '994 Manitowish Street', '72-084-0839', 'Elgar', '11 International Junction', '755-61-2758', 'Carson City', 'Nevada', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Esme Hurdle', '24 Milwaukee Way', '70-260-1158', 'Pearson', '27 Sachs Lane', '803-24-0932', 'Des Moines', 'Iowa', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Jerald Rowell', '97384 Lukken Crossing', '07-108-6059', 'Becker', '6 Arizona Plaza', '810-87-1630', 'Washington', 'District of Columbia', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Abbe Eeles', '8 Dahle Park', '89-244-5539', 'Valley Edge', '95455 Garrison Avenue', '208-68-3743', 'Memphis', 'Tennessee', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Gerrie Nowland', '5690 Colorado Crossing', '74-937-9013', 'Algoma', '85278 Steensland Way', '402-49-0402', 'Montgomery', 'Alabama', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Kare Buckney', '916 Vermont Drive', '56-588-8324', 'Lerdahl', '1 Tomscot Junction', '243-31-9577', 'Oklahoma City', 'Oklahoma', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Libbey Gley', '7 Calypso Way', '64-650-5449', 'Spenser', '3694 Lighthouse Bay Road', '244-13-4485', 'Lexington', 'Kentucky', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Wenonah Reading', '716 Longview Point', '61-790-4568', 'Brickson Park', '75 Mayfield Point', '612-81-8291', 'Washington', 'District of Columbia', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Waldon Vinter', '63470 Nobel Avenue', '27-933-5607', 'Harper', '4 Towne Park', '850-14-2009', 'Denver', 'Colorado', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Donia Mettricke', '9 Spenser Terrace', '75-995-8874', 'Kim', '404 Walton Court', '188-07-1811', 'Idaho Falls', 'Idaho', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Lily Donnell', '105 Scoville Junction', '29-673-0977', 'Golf View', '0197 Westend Terrace', '266-52-4708', 'White Plains', 'New York', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Gail Kulvear', '4 Aberg Road', '87-064-3768', 'Cambridge', '604 Lukken Way', '680-81-5614', 'El Paso', 'Texas', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Garik Harkess', '915 Dennis Circle', '28-819-1971', 'Messerschmidt', '9 Lunder Avenue', '564-56-8135', 'Des Moines', 'Iowa', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Adoree Arnoud', '392 Fieldstone Pass', '58-051-5158', 'Gina', '00098 Roth Hill', '838-11-0376', 'Greensboro', 'North Carolina', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Hannis Coxon', '5 Tony Pass', '68-758-8178', 'Knutson', '3176 Bunting Parkway', '286-90-8505', 'Montgomery', 'Alabama', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Kamila Pelman', '44199 Green Ridge Way', '66-618-4518', 'Eagan', '644 Montana Drive', '373-34-2172', 'El Paso', 'Texas', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Barnett Leyman', '3 Boyd Way', '48-204-8936', 'Hudson', '9 Sunfield Point', '398-11-1140', 'San Jose', 'California', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Joanne Marques', '6 Riverside Junction', '58-126-8415', 'Carberry', '2 Bobwhite Park', '729-36-2543', 'Washington', 'District of Columbia', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Tersina Thorlby', '221 Delladonna Drive', '70-782-2214', 'Hollow Ridge', '242 Golf Course Center', '563-07-4591', 'Indianapolis', 'Indiana', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Bari Scotting', '86946 Cordelia Terrace', '25-331-2388', 'Everett', '0 Merry Parkway', '320-57-1290', 'Orlando', 'Florida', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Hasty Kingsworth', '680 Novick Hill', '54-438-5354', 'Merchant', '70369 Coolidge Way', '832-42-2602', 'Omaha', 'Nebraska', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Miran Heisham', '94 Petterle Trail', '24-741-6568', 'Hintze', '980 Merry Crossing', '877-03-5341', 'Orlando', 'Florida', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Sandy Senecaut', '28 Riverside Lane', '61-683-7693', 'Montana', '1045 Crescent Oaks Center', '386-19-8604', 'Little Rock', 'Arkansas', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Melisenda Antonignetti', '707 Thierer Pass', '21-533-8713', 'Kim', '4 Forest Drive', '211-62-7418', 'Pittsburgh', 'Pennsylvania', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Abbott Paolozzi', '134 Mcbride Point', '67-149-8351', 'Ilene', '1 Sunbrook Pass', '865-82-6403', 'Stockton', 'California', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Teddie Vandrill', '77 Ramsey Avenue', '18-411-1872', 'Charing Cross', '217 8th Way', '653-65-8677', 'Panama City', 'Florida', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Adeline Aysik', '25351 Waxwing Pass', '05-738-6218', 'Randy', '2605 Tennessee Center', '143-61-9729', 'Miami', 'Florida', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Merwyn Olesen', '794 Clyde Gallagher Center', '50-986-3539', 'Northview', '4048 Hayes Junction', '381-51-1941', 'New Castle', 'Pennsylvania', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Nollie Saffe', '98666 Anhalt Alley', '34-745-8921', 'Anderson', '48 Holy Cross Alley', '784-96-1813', 'Cedar Rapids', 'Iowa', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Rubia Banstead', '7 Thackeray Point', '60-592-3842', 'Goodland', '93027 Dapin Plaza', '705-29-5234', 'Sparks', 'Nevada', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Randall D'' Angelo', '4719 Cardinal Park', '91-096-6594', 'Marcy', '9647 Haas Alley', '709-01-1838', 'Seattle', 'Washington', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Frederik Cumes', '3 Bowman Pass', '61-576-0825', 'Pawling', '87 Menomonie Terrace', '706-56-7908', 'Seattle', 'Washington', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Frederica O'' Mulderrig', '8673 Washington Park', '63-754-9323', 'Jenifer', '5 Westport Circle', '539-40-8103', 'Des Moines', 'Iowa', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Simeon McTurk', '606 Bashford Avenue', '17-307-9482', 'Linden', '84 Westridge Trail', '866-42-3828', 'Corpus Christi', 'Texas', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Augustus Buer', '39 Southridge Road', '36-238-2785', 'Ilene', '43264 Parkside Circle', '878-19-5287', 'Philadelphia', 'Pennsylvania', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Liesa Fibbitts', '03957 Delladonna Plaza', '33-908-1761', 'Mccormick', '5173 Barby Hill', '257-78-3030', 'Dayton', 'Ohio', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Gunner Moss', '62 Northview Pass', '70-138-7487', 'Sheridan', '18 Mitchell Avenue', '891-39-2652', 'Frederick', 'Maryland', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Ilyssa Laterza', '579 Center Center', '42-057-8759', 'Heffernan', '11 Sugar Circle', '642-80-4612', 'North Hollywood', 'California', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Graham Simanek', '92 Mendota Place', '66-567-9162', 'Russell', '34913 Charing Cross Way', '602-82-0675', 'Memphis', 'Tennessee', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Abran Cromett', '630 Dayton Way', '61-026-6645', 'Anthes', '150 Rutledge Avenue', '878-95-9404', 'El Paso', 'Texas', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Biddie MacGeaney', '8 Gateway Junction', '71-799-4473', 'Cody', '2 Independence Point', '511-79-7235', 'Birmingham', 'Alabama', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Pippa Fanstone', '6502 Butterfield Trail', '54-626-4692', 'Thackeray', '57 Dayton Hill', '875-48-2771', 'Pueblo', 'Colorado', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Eldon Chessell', '51 Lake View Avenue', '63-927-6636', 'South', '6 Kedzie Junction', '265-52-8181', 'Sacramento', 'California', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Astrix Borth', '9 Pierstorff Circle', '23-993-8140', 'Clemons', '2 Roxbury Crossing', '170-11-9420', 'Des Moines', 'Iowa', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Etti Yakubovics', '0256 Shasta Center', '99-798-7575', 'Milwaukee', '01175 Fairfield Terrace', '776-35-3630', 'Mesa', 'Arizona', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Norene Klug', '0320 Anthes Hill', '74-435-0866', 'Atwood', '7036 Ridgeway Point', '313-48-7795', 'Memphis', 'Tennessee', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Ibrahim Frogley', '6 Eggendart Street', '20-965-5511', 'Portage', '8 Sullivan Crossing', '603-48-4632', 'Seattle', 'Washington', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Angie Craiker', '5 Maple Junction', '26-880-6671', 'Dunning', '033 Harbort Way', '627-02-5989', 'Topeka', 'Kansas', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Weylin Rylstone', '5 Warrior Crossing', '01-404-7550', 'Washington', '0 Lerdahl Crossing', '207-02-7796', 'San Antonio', 'Texas', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Daria O''Lenechan', '639 Fordem Circle', '05-653-6275', 'Straubel', '55 American Ash Lane', '100-42-4106', 'El Paso', 'Texas', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Torrance Soigne', '8 Anniversary Point', '51-533-3364', 'Commercial', '2532 Elka Plaza', '599-93-0433', 'Moreno Valley', 'California', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Madel Pankhurst.', '64 Monica Circle', '80-613-9086', 'Hayes', '02227 Pepper Wood Pass', '489-66-7779', 'El Paso', 'Texas', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Merle Ingraham', '26 Lukken Way', '62-828-4756', 'Novick', '21800 Oak Drive', '151-12-2389', 'Sioux Falls', 'South Dakota', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Malissia Follos', '75263 Schiller Parkway', '95-404-8358', 'Orin', '154 Westridge Trail', '309-67-5442', 'West Hartford', 'Connecticut', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Sammie Dyble', '451 Mifflin Pass', '00-918-5682', 'Evergreen', '7693 Glacier Hill Street', '554-85-1316', 'Salt Lake City', 'Utah', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Kory Burris', '092 Grasskamp Place', '16-339-5695', 'Bayside', '43416 Dixon Terrace', '518-15-5805', 'Houston', 'Texas', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Laurent Aneley', '3 Claremont Alley', '13-413-4147', 'North', '1 Brickson Park Center', '108-70-2914', 'Abilene', 'Texas', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Somerset Keepence', '0 Basil Avenue', '39-654-3234', 'Warrior', '9 Chinook Court', '812-99-0192', 'Las Vegas', 'Nevada', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Janela Pynn', '65 Ronald Regan Drive', '52-440-4353', 'Buhler', '1693 Vidon Center', '701-60-4978', 'Charleston', 'West Virginia', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Lucretia Russon', '16580 Artisan Trail', '60-713-3097', 'Dexter', '8 Fairfield Way', '221-53-3561', 'San Antonio', 'Texas', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Ann-marie Easen', '7994 Heath Alley', '34-164-7067', 'Cambridge', '8198 Veith Parkway', '814-47-2400', 'Tampa', 'Florida', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Tibold Sigart', '55 Cordelia Lane', '74-850-2635', 'Glacier Hill', '6989 Dryden Pass', '150-57-8318', 'Des Moines', 'Iowa', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Dee dee Normavell', '14030 Veith Lane', '50-691-9476', 'John Wall', '03756 American Ash Terrace', '601-59-4746', 'Huntington', 'West Virginia', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Wilie Drakeford', '829 Maple Wood Plaza', '73-063-7547', 'Schiller', '778 David Pass', '270-72-5817', 'Houston', 'Texas', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Gordon Daniello', '0415 Havey Point', '20-203-3507', 'Debra', '21 Melvin Drive', '224-52-8188', 'Laredo', 'Texas', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Joaquin MacKomb', '874 Lien Park', '37-898-8349', 'Division', '7 Scott Road', '300-18-6915', 'Washington', 'District of Columbia', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Eyde Torritti', '2 Stoughton Terrace', '48-837-8993', 'Susan', '0718 Loeprich Center', '339-50-6013', 'Albuquerque', 'New Mexico', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Quinta Duetschens', '975 Oneill Center', '25-801-3461', 'Moland', '70 Sunbrook Junction', '373-57-6979', 'Yonkers', 'New York', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Erin Hoffner', '64 Acker Junction', '64-971-5843', 'Killdeer', '4248 Messerschmidt Trail', '123-01-5369', 'Virginia Beach', 'Virginia', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Lillis Shailer', '580 Rigney Hill', '96-435-7774', 'Ilene', '47352 Starling Pass', '811-26-7179', 'Denver', 'Colorado', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Filip Waren', '07 Oneill Hill', '95-025-6415', 'Blaine', '26040 Shelley Terrace', '222-57-5922', 'Louisville', 'Kentucky', true);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Jocelin Beckley', '00963 Cody Avenue', '26-057-6703', 'Thackeray', '187 Beilfuss Road', '455-47-9042', 'New Castle', 'Pennsylvania', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Olivie Gallichiccio', '965 Moland Plaza', '23-069-2575', 'Summerview', '44914 Kropf Terrace', '525-23-5582', 'Tucson', 'Arizona', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Edith Habgood', '8 Homewood Plaza', '88-389-2319', 'Tony', '1669 Stephen Place', '728-76-0583', 'Colorado Springs', 'Colorado', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Allison Gueny', '276 Fair Oaks Drive', '05-821-3287', 'Eastwood', '79520 Namekagon Court', '218-97-7804', 'Albany', 'New York', false);
insert into persona (nombre, direccion, numero, complemento, barrio, cep, ciudad, estado, activo) values ('Hilary Ketcher', '670 Katie Center', '01-737-9764', 'Summit', '709 Hoffman Point', '403-88-9007', 'Wichita', 'Kansas', true);